M48
; DRILL file {KiCad 7.0.1} date Sat Jan  6 20:51:46 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-06T20:51:46-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X3.9499Y-2.475
X3.9499Y-2.7026
T2
X3.87Y-1.565
X3.87Y-4.79
X5.34Y-1.565
X5.34Y-4.79
T0
M30
